### ISSUE TITLE
Error Stamen

### ISSUE THREAD

**Issue by marcelo136** [EL-BID/UrbanTrips#149]
Hola, 

cuando corro create_viz.py me da este error: 

AttributeError: Stamen

**Comment by marcelo136** [comment]
Esto ocurre tanto con la tabla de prueba como con una tabla que tengo de SUBE

**Comment by alephcero** [comment]
Hola @marcelo136, podrías copiar el mensaje de la consola para poder diagnosticar mejor el error? Esto se debe a que Stamen ya no es un proveedor de tiles para  `contextily`, pero debería estar solucionado. Hiciste una instalación nueva de `master`? porque en [este hotfix ](https://github.com/EL-BID/UrbanTrips/releases/tag/v0.2.3) lo habíamos resuelto

**Comment by marcelo136** [comment]
visualize_route_section_load (2024-05-30 16:01:29)
--------------------------------------------------
Produciendo grafico de ocupacion por tramos 8
Traceback (most recent call last):
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\xyzservices\lib.py", line 44, in __getattr__
    return self.__getitem__(key)
KeyError: 'Stamen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Investigacion\UrbanTrips\urbantrips\create_viz.py", line 46, in <module>
    main()
  File "E:\Investigacion\UrbanTrips\urbantrips\create_viz.py", line 33, in main
    viz.visualize_route_section_load(
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\utils\utils.py", line 25, in wrap
    result = f(*args, **kw)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\viz\viz.py", line 121, in visualize_route_section_load
    table.groupby('id_linea').apply(
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1766, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1815, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\ops.py", line 905, in apply_groupwise
    res = f(group)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1754, in f
    return func(g, *args, **kwargs)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\viz\viz.py", line 547, in viz_etapas_x_tramo_recorrido
    prov = cx.providers.Stamen.TonerLite
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\xyzservices\lib.py", line 46, in __getattr__
    raise AttributeError(key) from err
AttributeError: Stamen

**Comment by marcelo136** [comment]
Hola, baje el archivo arreglado que me paasaste, pero sigue tirando el mismo error. Cuando decís una instalación master, a que te referís? seguí los pasos que aparece en la documentación, y la instalación esta vez la realicé en una máquina donde nunca lo había corrido el programa. Lo hice en linux y en windows y el error es el mismo.

**Comment by alephcero** [comment]
@marcelo136 la [nueva release](https://github.com/EL-BID/UrbanTrips/releases/tag/v0.2.5) tiene un hotfix para este problema.  Si haces una instalación nueva desde cero debería resolverse. Si no es así dejanos un comentario.

**Comment by marcelo136** [comment]
Funcionó de 10, muchísimas gracias!!!!
