### ISSUE TITLE
Remove Stamen from viz_etapas_x_tramo_recorrido() 

### ISSUE THREAD

**Issue by alephcero** [EL-BID/UrbanTrips#150]
Remove stamen [here](https://github.com/EL-BID/UrbanTrips/blob/main/urbantrips/viz/viz.py#L547-L556), related to #149

**Comment by marcelo136** [comment]
mismo error, eliminando esa parte del codigo:

visualize_route_section_load (2024-05-31 16:29:37)
--------------------------------------------------
Produciendo grafico de ocupacion por tramos 8
Traceback (most recent call last):
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\xyzservices\lib.py", line 44, in __getattr__
    return self.__getitem__(key)
KeyError: 'Stamen'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Investigacion\UrbanTrips\urbantrips\create_viz.py", line 46, in <module>
    main()
  File "E:\Investigacion\UrbanTrips\urbantrips\create_viz.py", line 33, in main
    viz.visualize_route_section_load(
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\utils\utils.py", line 25, in wrap
    result = f(*args, **kw)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\viz\viz.py", line 121, in visualize_route_section_load
    table.groupby('id_linea').apply(
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1766, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1815, in _python_apply_general
    values, mutated = self.grouper.apply_groupwise(f, data, self.axis)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\ops.py", line 905, in apply_groupwise
    res = f(group)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\pandas\core\groupby\groupby.py", line 1754, in f
    return func(g, *args, **kwargs)
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\urbantrips\viz\viz.py", line 547, in viz_etapas_x_tramo_recorrido
    prov = cx.providers.Stamen.TonerLite
  File "C:\Users\front\anaconda3\envs\Urban_env\lib\site-packages\xyzservices\lib.py", line 46, in __getattr__
    raise AttributeError(key) from err
AttributeError: Stamen
