### ISSUE TITLE
Crash read_data_for_daily_kpi()

### ISSUE THREAD

**Issue by alephcero** [EL-BID/UrbanTrips#94]
`read_data_for_daily_kpi()` crashes on 1% sample
```
No existe tabla GPS en la base (no se pudeden computar indicadores de oferta)
Traceback (most recent call last):
  File "/home/pipe/proyectos/urbantrips/testeo/UrbanTrips/urbantrips/run_postprocessing.py", line 29, in <module>
    main()
  File "/home/pipe/proyectos/urbantrips/testeo/UrbanTrips/urbantrips/run_postprocessing.py", line 25, in main
    kpi.compute_kpi()
  File "/home/pipe/proyectos/urbantrips/testeo/UrbanTrips/venv/lib/python3.10/site-packages/urbantrips/utils/utils.py", line 25, in wrap
    result = f(*args, **kw)
  File "/home/pipe/proyectos/urbantrips/testeo/UrbanTrips/venv/lib/python3.10/site-packages/urbantrips/kpi/kpi.py", line 48, in compute_kpi
    legs, gps = read_data_for_daily_kpi()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by alephcero** [comment]
Closed by https://github.com/EL-BID/UrbanTrips/commit/d404669c2d03a5d855e8722526643d7c5303cc01
